PRA-Infoeduka/Areas/Admin/Controllers/AdminNotificationController.cs
using DAL.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PRA_Infoeduka.Models;

namespace PRA_Infoeduka.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminNotificationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AdminNotificationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult AllNotifications()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllNotifications()
        {
            var allNotifications = _unitOfWork.Notification.GetAll(includeProperties: "Course,User");

            return Json(new
            {
                data = allNotifications
            });
        }

        public IActionResult EditNotification(int id)
        {
            try
            {
                var notification = _unitOfWork.Notification.GetFirstOrDefault(x => x.Id == id);

                if (notification == null)
                {
                    return NotFound();
                }

                NotificationVM notificationVM = new()
                {
                    Notification = notification,
                    Courses = _unitOfWork.Course.GetAll().Select(c => new SelectListItem
                    {
                        Text = c.Name,
                        Value = c.Id.ToString()
                    })
                };

                return View(notificationVM);
            }
            catch
            {
                return RedirectToAction("AllCourses");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditNotification(NotificationVM notificationVM)
        {
            try
            {
                var notification = _unitOfWork.Notification.GetFirstOrDefault(x => x.Id == notificationVM.Notification.Id);

                if(notification == null) return NotFound();

                notification.Title = notificationVM.Notification.Title;
                notification.Description = notificationVM.Notification.Description;
                notification.ExpirationDate = notificationVM.Notification.ExpirationDate;
                notification.CourseId = notificationVM.Notification.CourseId;

                _unitOfWork.Save();

                return View("AllNotifications");
            }
            catch
            {
                return View(notificationVM);
            }
        }

        [HttpDelete]
        public IActionResult DeleteNotification(int id)
        {
            try
            {
                var currentNotification = _unitOfWork.Notification.GetFirstOrDefault(x => x.Id == id);

                if (id == 0)
                {
                    return Json(new
                    {
                        success = false
                    });
                }

                _unitOfWork.Notification.Delete(currentNotification);
                _unitOfWork.Save();

                return Json(new
                {
                    success = true
                });
            }
            catch
            {
                return Json(new
                {
                    success = false
                });
            }
        }
    }
}

PRA-Infoeduka/Areas/Admin/Controllers/CourseController.cs
using DAL.Models;
using DAL.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace PRA_Infoeduka.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CourseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CourseController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult AllCourses()
        {
            return View();
        }

        public IActionResult CreateCourse()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCourse(Course course)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(course);
                }

                _unitOfWork.Course.Add(course);

                _unitOfWork.Save();

                return RedirectToAction("AllCourses");
            }
            catch
            {
                return View(course);
            }
        }

        public IActionResult EditCourse(string id)
        {
            try
            {
                var course = _unitOfWork.Course.GetFirstOrDefault(x => x.Id == id);

                if (course == null)
                {
                    return NotFound();
                }

                return View(course);
            }
            catch 
            {
                return RedirectToAction("AllCourses");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCourse(Course course)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(course);
                }

                _unitOfWork.Course.Update(course);
                _unitOfWork.Save();

                return RedirectToAction("AllCourses");
            }
            catch
            {
                return View(course);
            }
        }

        [HttpGet]
        public IActionResult GetAllCourses()
        {
            var allCourses = _unitOfWork.Course.GetAll();

            return Json(new
            {
                data = allCourses
            });
        }

        [HttpDelete]
        public IActionResult DeleteCourse(string id)
        {
            try
            {
                var currentCourse = _unitOfWork.Course.GetFirstOrDefault(x => x.Id == id);

                if (id == null)
                {
                    return Json(new
                    {
                        success = false
                    });
                }

                _unitOfWork.Course.Delete(currentCourse);
                _unitOfWork.Save();

                return Json(new
                {
                    success = true
                });
            }
            catch 
            {
                return Json(new
                {
                    success = false
                });
            }
        }

    }
}

PRA-Infoeduka/Areas/Admin/Controllers/ProfessorController.cs
using DAL.Models;
using DAL.Repositories.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PRA_Infoeduka.Models;
using Utilities;

namespace PRA_Infoeduka.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProfessorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<AppUser> _userManager;

        public ProfessorController(
            IUnitOfWork unitOfWork,
            UserManager<AppUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public IActionResult AllProfessors()
        {
            return View();
        }

        public IActionResult Details(string id)
        {
            try
            {
                var professor = _unitOfWork.AppUser.GetFirstOrDefault(x => x.Id == id, includeProperties: "ProfessorCourses");

                if(professor == null) return NotFound();

                ProfessorVM professorVM = new()
                {
                    Professor = professor,
                    Courses = _unitOfWork.Course.GetAll().Select(c => new SelectListItem
                    {
                        Text = c.Name,
                        Value = c.Id.ToString()
                    }),
                    CurrentCourses = professor.ProfessorCourses.Select(pc => pc.Course)
                };

                return View(professorVM);
            }
            catch
            {
                return RedirectToAction("AllProfessors");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProfessorVM professorVM)
        {
            try
            {
                var courses = JsonConvert.DeserializeObject<List<string>>(professorVM.SelectedCourses);

                var professorForUpdate = _unitOfWork.AppUser.GetFirstOrDefault(p => p.Id == professorVM.Professor.Id, includeProperties: "ProfessorCourses.Course");

                professorForUpdate.FirstName = professorVM.Professor.FirstName;
                professorForUpdate.LastName = professorVM.Professor.LastName;
                professorForUpdate.Email = professorVM.Professor.Email;

                var coursesForRemove = professorForUpdate.ProfessorCourses.Where(pc => !courses.Contains(pc.CourseId));
                coursesForRemove.ToList().ForEach(pc => _unitOfWork.ProfessorCourse.Delete(pc));

                var currentCourses = professorForUpdate.ProfessorCourses.Select(pc => pc.Course.Id);
                var newCourses = courses.Except(currentCourses);

                foreach (var newCourse in newCourses)
                {
                    var courseFromDb = _unitOfWork.Course.GetFirstOrDefault(c => c.Id == newCourse);
                    if (courseFromDb == null) continue;

                    professorForUpdate.ProfessorCourses.Add(new ProfessorCourse
                    {
                        Professor = professorForUpdate,
                        Course = courseFromDb
                    });
                }

                _unitOfWork.Save();

                return RedirectToAction("AllProfessors");
            }
            catch
            {
                return View(professorVM);
            }
        }

        [HttpGet]
        public IActionResult GetAllProfessors()
        {
            var allProfessors = _userManager.GetUsersInRoleAsync(Constants.PROFESSOR_ROLE).GetAwaiter().GetResult();

            return Json(new
            {
                data = allProfessors
            });
        }

        [HttpDelete]
        public IActionResult DeleteProfessor(string id)
        {
            var professorForDelete = _unitOfWork.AppUser.GetFirstOrDefault(p => p.Id == id);

            if (professorForDelete == null)
                return Json(new { success = false });

            _unitOfWork.AppUser.Delete(professorForDelete);
            _unitOfWork.Save();

            return Json(new { success = true });
        }
    }
}

PRA-Infoeduka/Areas/Professor/Controllers/MyNotificationController.cs
using DAL.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PRA_Infoeduka.Models;
using System.Security.Claims;

namespace PRA_Infoeduka.Areas.Professor.Controllers
{
    [Area("Professor")]
    public class MyNotificationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public MyNotificationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult AllMyNotifications()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllMyNotifications()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var professorNotifications = _unitOfWork.Notification.GetAll(n => n.User.Id == userId.Value, includeProperties:"Course");

            return Json(new
            {
                data = professorNotifications
            });
        }

        public IActionResult EditMyNotification(int id)
        {
            var notification = _unitOfWork.Notification.GetFirstOrDefault(x => x.Id == id);

            if (notification == null)
            {
                return NotFound();
            }

            NotificationVM notificationVM = new()
            {
                Notification = notification,
                Courses = _unitOfWork.Course.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
            };

            return View(notificationVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditMyNotification(NotificationVM notificationVM)
        {
            try
            {
                var notification = _unitOfWork.Notification.GetFirstOrDefault(x => x.Id == notificationVM.Notification.Id);

                if (notification == null) return NotFound();

                notification.Title = notificationVM.Notification.Title;
                notification.Description = notificationVM.Notification.Description;
                notification.ExpirationDate = notificationVM.Notification.ExpirationDate;
                notification.CourseId = notificationVM.Notification.CourseId;

                _unitOfWork.Save();

                return View("AllMyNotifications");
            }
            catch
            {
                return View(notificationVM);
            }
        }

        [HttpDelete]
        public IActionResult DeleteMyNotification(int id)
        {
            try
            {
                var currentNotification = _unitOfWork.Notification.GetFirstOrDefault(x => x.Id == id);

                if (id == 0)
                {
                    return Json(new
                    {
                        success = false
                    });
                }

                _unitOfWork.Notification.Delete(currentNotification);
                _unitOfWork.Save();

                return Json(new
                {
                    success = true
                });
            }
            catch
            {
                return Json(new
                {
                    success = false
                });
            }
        }
    }
}

PRA-Infoeduka/Views/Shared/_Layout.cshtml
@using Utilities;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRA_Infoeduka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRA_Infoeduka.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/algebraLogo.png" width="100" height="50" class="mx-3" />
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if(User.Identity.IsAuthenticated){
                        @if (User.IsInRole(Constants.ADMIN_ROLE))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Admin" asp-controller="Professor" asp-action="AllProfessors">Professors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Admin" asp-controller="Course" asp-action="AllCourses">Courses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Admin" asp-controller="AdminNotification" asp-action="AllNotifications">All notifications</a>
                                </li>
                            </ul>
                        }

                        @if (User.IsInRole(Constants.PROFESSOR_ROLE))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Professor" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Professor" asp-controller="ProfessorCourse" asp-action="AllProfessorCourses">Courses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Professor" asp-controller="MyNotification" asp-action="AllMyNotifications">My notifications</a>
                                </li>
                            </ul>
                        }
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container" style="height: 80px">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>